### ISSUE TITLE
Issues with npm@2

### ISSUE THREAD

**Issue by piuccio** [MailOnline/eslint-config-mailonline#10]
npm2 doesn't use the same flat structure of npm3 so when using this preset you end up with errors like `ESLint couldn't find the plugin "eslint-plugin-no-use-extend-native".`

Once you install all plugin dependencies manually you get

```
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at EventEmitter.ReturnStatement (/cc/node_modules/eslint-plugin-promise/rules/no-return-wrap.js:25:28)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/cc/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/cc/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/cc/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/cc/node_modules/eslint/lib/eslint.js:925:36)
    at Controller.__execute (/cc/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/cc/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/cc/node_modules/eslint/lib/util/traverser.js:36:33)
```

**Comment by claudiorodriguez** [comment]
Unfortunately, closing this as we will only support `npm@3` and upwards. If anyone needs the package to work with version `2` or less, I'd recommend making a fork of the project and perhaps copying over the rulesets from `canonical`.
